# Generated by Django 6.0.5 on 2026-06-01 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000000000000000.0), django.core.validators.MaxValueValidator(1000000000000000.0)])),
                ('num2', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000000000000000.0), django.core.validators.MaxValueValidator(1000000000000000.0)])),
                ('operation', models.CharField(choices=[('add', '➕ Сложение'), ('subtract', '➖ Вычитация'), ('multiply', '✖️ Умножение'), ('divide', '➗ Деление')], max_length=10)),
                ('result', models.FloatField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
